apiVersion: apps/v1
kind: Deployment
metadata:
  name: moresapigatewaypm-depl
spec:
  selector: 
    matchLabels:
      app: moresapigatewaypm
  replicas: 1
  template:
    metadata:
      labels:
        app: moresapigatewaypm
    spec:
      containers:
        - name: moresapigatewaypm
          image: moresacr.azurecr.io/hugsr8/moresapigateway
          ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: moresapigatewaypm-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  selector:
    app: moresapigatewaypm
